---
- name: Setup sensible defaults
  shell: source sensible_osx_defaults.sh >> default_settings_log.txt chdir=~/.ansible/workstation/shell_scripts

- name: Add homebrew taps
  homebrew_tap: tap={{ item }}
  with_items:
    - caskroom/cask
    - caskroom/fonts

- name: Install Homebrew cask
  homebrew: name=cask state=latest

- name: Update homebrew recipes
  shell: brew update

- name: Install packages from homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - cask
    - wget
    - git
    - hub
    - tmux
    - ag
    - w3m
    - csshx
    - rbenv
    - mplayer

- name: Install ruby-build
  git: repo=https://github.com/rbenv/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: Install GUI apps
  homebrew_cask: name={{ item }} state=present
  with_items:
    - font-hack
    - caffeine
    - shiftit
    - xquartz
    - flycut
    - ccmenu
    - google-chrome
  ignore_errors: true

- include: install_emacs.yml

- include: install_bash_it.yml

- name: Update .bashrc file
  blockinfile:
    path: ~/.bashrc
    create: yes
    block: |
      export PATH="/usr/local/bin:$PATH"

      # Path to the bash it configuration
      export BASH_IT="/Users/$USER/.bash_it"

      # Lock and Load a custom theme file
      export BASH_IT_THEME="bobby"

      # Load Bash It
      source $BASH_IT/bash_it.sh

      # Enable colours in terminal
      export TERM=xterm-256color

- name: Update .bash_profile file
  lineinfile:
    dest: ~/.bash_profile
    regexp: '^source ~/.bashrc'
    line: 'source ~/.bashrc'
    state: present
    create: yes

- name: Setup git
  shell: "git config --global alias.{{ item.key }} {{ item.value }}"
  with_dict:
    st: status
    co: checkout
