---
- name: Setup sensible defaults
  shell: source sensible_osx_defaults.sh >> default_settings_log.txt chdir=~/.ansible/workstation/shell_scripts

- name: Add homebrew taps
  homebrew_tap: tap={{ item }}
  with_items:
    - homebrew/dupes
    - caskroom/fonts
    - caskroom/cask
    - nviennot/tmate

- name: Install Homebrew cask
  homebrew: name=brew-cask state=present

- name: Update homebrew recipes
  shell: brew update

- name: Install packages from homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - cask
    - wget
    - git
    - hub
    - tmux
    - imagemagick
    - ag
    - ctags
    - w3m
    - csshx
    - nginx
    - postgresql
    - tmate

- name: Install GUI apps
  homebrew_cask: name={{ item }} state=present
  with_items:
    - google-chrome
    - virtualbox
    - caffeine
    - dash
    - shiftit
    - ccmenu
    - tunnelblick
    - mou
    - xscope

- include: install_bash_it.yml

- include: install_emacs.yml

# User specific settings
- include: "{ ansible_user_id }.yml"

- template: src=~/.ansible/workstation/templates/.bashrc dest=~/.bashrc

- template: src=~/.ansible/workstation/templates/.bash_profile dest=~/.bash_profile

- name: Upgrade any already-installed formulae
  shell: brew upgrade

- name: Remove outdated versions from the cellar
  shell: brew cleanup