---
- name: Setup sensible defaults
  shell: source sensible_osx_defaults.sh >> default_settings_log.txt chdir=~/.ansible/workstation/shell_scripts

- name: Add homebrew taps
  homebrew_tap: tap={{ item }}
  with_items:
    - caskroom/cask

- name: Install Homebrew cask
  homebrew: name=cask state=latest

- name: Update homebrew recipes
  shell: brew update

- name: Install packages from homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - cask
    - wget
    - git
    - hub
    - tmux
    - ag
    - w3m
    - csshx
    - rbenv
    - rbenv-gemset

- name: Install ruby-build
  git: repo=https://github.com/rbenv/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: Install GUI apps
  homebrew_cask: name={{ item }} state=present
  with_items:
    - caffeine
    - shiftit
    - mou
    - flycut
    - ccmenu
    - google-chrome
    - xquartz
  ignore_errors: true

- include: install_emacs.yml

- include: install_bash_it.yml

- template: src=~/.ansible/workstation/templates/.bashrc dest=~/.bashrc

- template: src=~/.ansible/workstation/templates/.bash_profile dest=~/.bash_profile

- name: Setup git
  shell: "git config --global alias.{{ item.key }} {{ item.value }}"
  with_dict:
    st: status
    co: checkout
