---
- name: Clone the bash-it repo
  git: repo=https://github.com/revans/bash-it.git dest=~/.bash_it

- name: Update .bash_profile
  shell: echo {{item}} >> ~/.bash_profile
  with_items:
    export PATH="/usr/local/bin:$PATH"
    export BASH_IT="~/.bash_it"
    export BASH_IT_THEME="bobby"
    source ~/.bash_it/bash_it.sh

- name: load environment variables via .bash_profile
  shell: source ~/.bash_profile

- name: Load bash-it
  shell: source $BASH_IT/bash_it.sh

- name: Retrieve list of custom scripts
  shell: ls ~/.ansible/workstation/shell_scripts/bash_it/custom
  register: custom_bash_it_scripts

- name: Link custom bash-it scripts
  file: src=~/.ansible/workstation/shell_scripts/bash_it/custom/{{item}} dest=~/.bash_it/custom/{{item}} state=link
  with_items:
    custom_bash_it_scripts

- name: Load customizations
  shell: source ~/.bash_it/custom/{{item}}
  with_items:
    custom_bash_it_scripts