---
- name: Clone the bash-it repo
  git: repo=https://github.com/revans/bash-it.git dest=~/.bash_it

- name: Link git user initials bash_it custom script
  file: src=~/.ansible/workstation/shell_scripts/bash_it/custom/add_user_initials_to_git_prompt_info.bash dest=~/.bash_it/custom/add_user_initials_to_git_prompt_info.bash state=link

- name: Link aliases bash_it custom script
  file: src=~/.ansible/workstation/shell_scripts/bash_it/custom/aliases.bash dest=~/.bash_it/custom/aliases.bash state=link

- name: ensure bash-it enabled plugins dir exists
  file: path=~/.bash_it/plugins/enabled state=directory

- name: Enable rbenv plugin
  file: src=~/.bash_it/plugins/available/rbenv.plugin.bash dest=~/.bash_it/plugins/enabled/rbenv.plugin.bash state=link

- name: ensure bash-it enabled completion dir exists
  file: path=~/.bash_it/completion/enabled state=directory

- name: enable bash completion
  file: src=~/.bash_it/completion/available/defaults.completion.bash dest=~/.bash_it/completion/enabled/defaults.completion.bash state=link

- name: enable  git completion
  file: src=~/.bash_it/completion/available/git.completion.bash      dest=~/.bash_it/completion/enabled/git.completion.bash state=link
