---
- name: Setup sensible defaults
  shell: source sensible_osx_defaults.sh >> default_settings_log.txt chdir=~/.ansible/workstation/shell_scripts

- name: Add homebrew taps
  homebrew_tap: tap={{item}}
  with_items:
    - homebrew/dupes
    - caskroom/fonts
    - caskroom/cask
    - nviennot/tmate

- name: Install Homebrew cask
  homebrew: name=brew-cask state=present
   
- name: Update homebrew recipes
  shell: brew update
  
- name: Install GNU core utilities (those that come with OS X are outdated). 
  homebrew: name=coreutils state=present 

- name: Install some other useful utilities like `sponge`.
  homebrew: name=moreutils state=present

- name: Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
  homebrew: name=findutils state=present

#- name: Install GNU `sed`, overwriting the built-in `sed`.
#  shell: brew install gnu-sed --with-default-names

#- name: Install Bash 4.
# Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before
# running `chsh`.
#  homebrew: name={{item}} state=present
# with_items:
#   - bash
#   - bash-completion

# name: Install more recent versions of some OS X tools
# homebrew: name=grep

# name: Update path in order to use gnu tools in place of the included mac ones
# shell: export PATH="$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH" 
#

- name: Install packages from homebrew
  homebrew: name={{item}} state=present
  with_items:
    - cask
    - wget
    - git
    - hub
    - tmux
    - imagemagick
    - ag
    - ctags
    - w3m
    - csshx
    - nginx
    - postgresql
    - tmate

- name: Install GUI apps
  homebrew_cask: name={{item}} state=present
  with_items:
    - google-chrome
    - virtualbox
    - caffeine
    - dash
    - skype
    - shiftit
    - vlc
    - ccmenu
    - tunnelblick
    - dropbox
    - cheatsheet
    - daisydisk
    - xscope
    - ember
    - kaleidoscope
    - paw
    - bartender
    - moom
    - mou

#- include: install_bash_it.yml

- template: src=~/.ansible/workstation/templates/.bashrc dest=~/.bashrc

- template: src=~/.ansible/workstation/templates/.bash_profile

- name: Install emacs
  shell: "brew install emacs --cocoa"

- name: Install emacs config
  git: repo=https://github.com/sufyanadam/.emacs-use-package.git dest=~/.emacs.d

- name: Run cask in .emacs.d directory
  shell: cd ~/.emacs.d && cask

- name: Upgrade any already-installed formulae
  shell: brew upgrade

- name: Remove outdated versions from the cellar
  shell: brew cleanup