---
- include: dev_box_essentials.yml

- include: personal/sufyan.yml

- name: Upgrade any already-installed formulae
  shell: brew upgrade

- name: Remove outdated versions from the cellar
  shell: brew cleanup
