- name: Install required software
  homebrew: name={{ item }} state=present
  with_items:
    - cask
    - wget
    - git
    - tmux
    - emacs install_options=cocoa,srgb

- name: Install GUI apps
  homebrew_cask: name={{ item }} state=present
  with_items:
    - google-chrome
    - virtualbox

- name: Install emacs config
  git: repo=https://github.com/sufyanadam/.emacs-use-package.git dest=~/.emacs.d

- name: Run cask in .emacs.d directory
  shell: cd ~/.emacs.d && cask

