---
- name: Install required software
  homebrew: name={{item}} state=present
  with_items:
    - cask
    - wget
    - git
    - tmux
    - imagemagick

- name: Tap caskroom/cask
  homebrew_tap: tap=caskroom/cask

- name: Install Homebrew cask
  homebrew: name=brew-cask

- name: Install GUI apps
  homebrew_cask: name={{item}} state=present
  with_items:
    - google-chrome
    - virtualbox
    - caffeine
    - dash
    - skype
    - shiftit
    - vlc
    - ccmenu
    - tunnelblick
    
- name: Install emacs
  shell: brew install emacs --cocoa --srgb 

- name: Install emacs config
  git: repo=https://github.com/sufyanadam/.emacs-use-package.git dest=~/.emacs.d

- name: Run cask in .emacs.d directory
  shell: cd ~/.emacs.d && cask
